export interface TeamPageDomRefs {
  appShellEl: HTMLElement
  toggleWindowSizeEl: HTMLButtonElement
  toggleFullscreenEl: HTMLButtonElement
  storeSummaryEl: HTMLElement
  chatListEl: HTMLElement
  chatTitleEl: HTMLElement
  chatSubtitleEl: HTMLElement
  chatStatusEl: HTMLElement
  messagesEl: HTMLElement
  roleSummaryEl: HTMLElement
  roleListEl: HTMLElement
  roleTemplateSelectEl: HTMLSelectElement
  templateListEl: HTMLElement
  targetPreviewEl: HTMLElement
  busyPreviewEl: HTMLElement
  composerFormEl: HTMLFormElement
  sendButtonEl: HTMLButtonElement
  messageInputEl: HTMLTextAreaElement
  referenceDraftEl: HTMLElement
  mentionPanelEl: HTMLElement
  errorEl: HTMLElement
  newChatNameEl: HTMLInputElement
  createChatFormEl: HTMLFormElement
  quickCreateChatEl: HTMLButtonElement
  templateNameEl: HTMLInputElement
  templateDescriptionEl: HTMLTextAreaElement
  templatePromptEl: HTMLTextAreaElement
  templateFormTitleEl: HTMLElement
  settingsButtonEl: HTMLButtonElement
  settingsMenuEl: HTMLElement
  openAllNotesEl: HTMLButtonElement
  closeAllNotesEl: HTMLButtonElement
  allNotesModalEl: HTMLElement
  allNotesListEl: HTMLElement
  openPeopleLibraryEl: HTMLButtonElement
  closePeopleLibraryEl: HTMLButtonElement
  peopleLibraryModalEl: HTMLElement
  personTemplateModalEl: HTMLElement
  addPersonModalEl: HTMLElement
  temporaryPersonModalEl: HTMLElement
  notesPanelEl: HTMLElement
  notesDragHandleEl: HTMLElement
  toggleNotesPanelEl: HTMLButtonElement
  closeNotesPanelEl: HTMLButtonElement
  globalNoteTabEl: HTMLButtonElement
  chatNoteTabEl: HTMLButtonElement
  notesEditorEl: HTMLElement
  noteBoldEl: HTMLButtonElement
  noteItalicEl: HTMLButtonElement
  noteStrikeEl: HTMLButtonElement
  noteBulletListEl: HTMLButtonElement
  noteOrderedListEl: HTMLButtonElement
  noteUndoEl: HTMLButtonElement
  noteRedoEl: HTMLButtonElement
  peopleLibrarySummaryEl: HTMLElement
  peopleLibraryListEl: HTMLElement
  peopleLibraryPaginationEl: HTMLElement
  addLibraryPeopleListEl: HTMLElement
  addPersonSearchEl: HTMLInputElement
  addPersonBuiltinTabEl: HTMLButtonElement
  addPersonCustomTabEl: HTMLButtonElement
  newTemplateEl: HTMLButtonElement
  closePersonTemplateEl: HTMLButtonElement
  closeAddPersonEl: HTMLButtonElement
  openTemporaryPersonEl: HTMLButtonElement
  closeTemporaryPersonEl: HTMLButtonElement
  addRoleFormEl: HTMLFormElement
  addLibraryPeopleFormEl: HTMLFormElement
  addTemporaryPersonFormEl: HTMLFormElement
  peopleLibraryFormEl: HTMLFormElement
  templateSiteGeminiEl: HTMLInputElement
  templateSiteChatGptEl: HTMLInputElement
  templateSiteClaudeEl: HTMLInputElement
  templateSiteDeepSeekEl: HTMLInputElement
  templateSiteQwenEl: HTMLInputElement
  templateSiteKimiEl: HTMLInputElement
  templateChatGptGptsFieldEl: HTMLElement
  templateChatGptGptsUrlEl: HTMLInputElement
  temporaryPersonNameEl: HTMLInputElement
  temporaryPersonDescriptionEl: HTMLTextAreaElement
  temporaryPersonPromptEl: HTMLTextAreaElement
  togglePeopleDrawerEl: HTMLButtonElement
  rolePanelEl: HTMLElement
  windowLauncherEl: HTMLButtonElement
  iframeHostEl: HTMLElement
}

export function requireElement<T extends Element>(selector: string): T {
  const element = document.querySelector<T>(selector)
  if (!element) throw new Error(`Missing element: ${selector}`)
  return element
}

export function createTeamPageDomRefs(): TeamPageDomRefs {
  return {
    appShellEl: requireElement<HTMLElement>('#app'),
    toggleWindowSizeEl: requireElement<HTMLButtonElement>('#toggle-window-size'),
    toggleFullscreenEl: requireElement<HTMLButtonElement>('#toggle-fullscreen'),
    storeSummaryEl: requireElement<HTMLElement>('#store-summary'),
    chatListEl: requireElement<HTMLElement>('#chat-list'),
    chatTitleEl: requireElement<HTMLElement>('#chat-title'),
    chatSubtitleEl: requireElement<HTMLElement>('#chat-subtitle'),
    chatStatusEl: requireElement<HTMLElement>('#chat-status'),
    messagesEl: requireElement<HTMLElement>('#messages'),
    roleSummaryEl: requireElement<HTMLElement>('#role-summary'),
    roleListEl: requireElement<HTMLElement>('#role-list'),
    roleTemplateSelectEl: requireElement<HTMLSelectElement>('#role-template-select'),
    templateListEl: requireElement<HTMLElement>('#template-list'),
    targetPreviewEl: requireElement<HTMLElement>('#target-preview'),
    busyPreviewEl: requireElement<HTMLElement>('#busy-preview'),
    composerFormEl: requireElement<HTMLFormElement>('#composer'),
    sendButtonEl: requireElement<HTMLButtonElement>('#send-message'),
    messageInputEl: requireElement<HTMLTextAreaElement>('#message-input'),
    referenceDraftEl: requireElement<HTMLElement>('#reference-draft'),
    mentionPanelEl: requireElement<HTMLElement>('#mention-panel'),
    errorEl: requireElement<HTMLElement>('#error'),
    newChatNameEl: requireElement<HTMLInputElement>('#new-chat-name'),
    createChatFormEl: requireElement<HTMLFormElement>('#create-chat-form'),
    quickCreateChatEl: requireElement<HTMLButtonElement>('#quick-create-chat'),
    templateNameEl: requireElement<HTMLInputElement>('#template-name'),
    templateDescriptionEl: requireElement<HTMLTextAreaElement>('#template-description'),
    templatePromptEl: requireElement<HTMLTextAreaElement>('#template-prompt'),
    templateFormTitleEl: requireElement<HTMLElement>('#template-form-title'),
    settingsButtonEl: requireElement<HTMLButtonElement>('#settings-button'),
    settingsMenuEl: requireElement<HTMLElement>('#settings-menu'),
    openAllNotesEl: requireElement<HTMLButtonElement>('#open-all-notes'),
    closeAllNotesEl: requireElement<HTMLButtonElement>('#close-all-notes'),
    allNotesModalEl: requireElement<HTMLElement>('#all-notes-modal'),
    allNotesListEl: requireElement<HTMLElement>('#all-notes-list'),
    openPeopleLibraryEl: requireElement<HTMLButtonElement>('#open-people-library'),
    closePeopleLibraryEl: requireElement<HTMLButtonElement>('#close-people-library'),
    peopleLibraryModalEl: requireElement<HTMLElement>('#people-library-modal'),
    personTemplateModalEl: requireElement<HTMLElement>('#person-template-modal'),
    addPersonModalEl: requireElement<HTMLElement>('#add-person-modal'),
    temporaryPersonModalEl: requireElement<HTMLElement>('#temporary-person-modal'),
    notesPanelEl: requireElement<HTMLElement>('#notes-panel'),
    notesDragHandleEl: requireElement<HTMLElement>('#notes-drag-handle'),
    toggleNotesPanelEl: requireElement<HTMLButtonElement>('#toggle-notes-panel'),
    closeNotesPanelEl: requireElement<HTMLButtonElement>('#close-notes-panel'),
    globalNoteTabEl: requireElement<HTMLButtonElement>('#global-note-tab'),
    chatNoteTabEl: requireElement<HTMLButtonElement>('#chat-note-tab'),
    notesEditorEl: requireElement<HTMLElement>('#notes-editor'),
    noteBoldEl: requireElement<HTMLButtonElement>('#note-bold'),
    noteItalicEl: requireElement<HTMLButtonElement>('#note-italic'),
    noteStrikeEl: requireElement<HTMLButtonElement>('#note-strike'),
    noteBulletListEl: requireElement<HTMLButtonElement>('#note-bullet-list'),
    noteOrderedListEl: requireElement<HTMLButtonElement>('#note-ordered-list'),
    noteUndoEl: requireElement<HTMLButtonElement>('#note-undo'),
    noteRedoEl: requireElement<HTMLButtonElement>('#note-redo'),
    peopleLibrarySummaryEl: requireElement<HTMLElement>('#people-library-summary'),
    peopleLibraryListEl: requireElement<HTMLElement>('#people-library-list'),
    peopleLibraryPaginationEl: requireElement<HTMLElement>('#people-library-pagination'),
    addLibraryPeopleListEl: requireElement<HTMLElement>('#add-library-people-list'),
    addPersonSearchEl: requireElement<HTMLInputElement>('#add-person-search'),
    addPersonBuiltinTabEl: requireElement<HTMLButtonElement>('#add-person-tab-builtin'),
    addPersonCustomTabEl: requireElement<HTMLButtonElement>('#add-person-tab-custom'),
    newTemplateEl: requireElement<HTMLButtonElement>('#new-template'),
    closePersonTemplateEl: requireElement<HTMLButtonElement>('#close-person-template'),
    closeAddPersonEl: requireElement<HTMLButtonElement>('#close-add-person'),
    openTemporaryPersonEl: requireElement<HTMLButtonElement>('#open-temporary-person'),
    closeTemporaryPersonEl: requireElement<HTMLButtonElement>('#close-temporary-person'),
    addRoleFormEl: requireElement<HTMLFormElement>('#add-role-form'),
    addLibraryPeopleFormEl: requireElement<HTMLFormElement>('#add-library-people-form'),
    addTemporaryPersonFormEl: requireElement<HTMLFormElement>('#add-temporary-person-form'),
    peopleLibraryFormEl: requireElement<HTMLFormElement>('#people-library-form'),
    templateSiteGeminiEl: requireElement<HTMLInputElement>('#template-site-gemini'),
    templateSiteChatGptEl: requireElement<HTMLInputElement>('#template-site-chatgpt'),
    templateSiteClaudeEl: requireElement<HTMLInputElement>('#template-site-claude'),
    templateSiteDeepSeekEl: requireElement<HTMLInputElement>('#template-site-deepseek'),
    templateSiteQwenEl: requireElement<HTMLInputElement>('#template-site-qwen'),
    templateSiteKimiEl: requireElement<HTMLInputElement>('#template-site-kimi'),
    templateChatGptGptsFieldEl: requireElement<HTMLElement>('#template-chatgpt-gpts-field'),
    templateChatGptGptsUrlEl: requireElement<HTMLInputElement>('#template-chatgpt-gpts-url'),
    temporaryPersonNameEl: requireElement<HTMLInputElement>('#temporary-person-name'),
    temporaryPersonDescriptionEl: requireElement<HTMLTextAreaElement>('#temporary-person-description'),
    temporaryPersonPromptEl: requireElement<HTMLTextAreaElement>('#temporary-person-prompt'),
    togglePeopleDrawerEl: requireElement<HTMLButtonElement>('#toggle-people-drawer'),
    rolePanelEl: requireElement<HTMLElement>('.role-panel'),
    windowLauncherEl: requireElement<HTMLButtonElement>('#window-launcher'),
    iframeHostEl: requireElement<HTMLElement>('#iframe-host'),
  }
}
